---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: ./node_modules/eslint-config-standard/eslintrc.json
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.ejs"
  - "**.jsx"
exclude_paths:
- test/
