language: node_js
node_js:
    - node
    - stable
before_install:
    - npm install -g npm@^2.0.0
    - npm install codecov codeclimate-test-reporter
before_script:
    - curl -Lo travis_after_all.py https://git.io/vLSON
script:
    - npm test
    - npm run coverage
after_success:
    - python travis_after_all.py
    - ./node_modules/.bin/codecov
    - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
    - npm run semantic-release
addons:
    code_climate:
        repo_token: 827ee77036124856822bfe501806bd0d5277493a1c07ef424e2e5a79ee414e7d
